# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtag',
            name='pretty_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logtag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
