# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170327_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtag',
            name='pretty_name',
        ),
        migrations.AddField(
            model_name='logtag',
            name='pretty',
            field=models.TextField(blank=True),
        ),
    ]
