# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20170327_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameserver',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='gameserver',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=2, editable=False),
            preserve_default=False,
        ),
    ]
