# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170327_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='game_avatars')),
                ('basedir', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Teams'),
        ),
    ]
