# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170327_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.Game'),
            preserve_default=False,
        ),
    ]
