# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20170327_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='game',
        ),
    ]
